blueprints/repo: Fix more pygit2 regressions
Otherwise this will happen:
  File "/usr/lib/python3.12/site-packages/gitsrht/blueprints/repo.py", line 148, in summary
    tags = [(ref, git_repo.get(git_repo.references[ref].raw_target))
                               ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.12/site-packages/pygit2/references.py", line 41, in __getitem__
    return self._repository.lookup_reference(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad argument type for built-in operation